### ISSUE TITLE
zorg n drop HAAAAAAAAAAAAATES all tracking sites.

### ISSUE THREAD

**Issue by JordanB-1337** [zorgtech/zorg-n-drop#9]
It hates hotjar, it hates lucky orange it hates zeerat, idk what to do now._

**Comment by haylinmoore** [comment]
Stop trying to track people 😂

**Comment by JordanB-1337** [comment]
Then how are we supposed to do anything :P

**Comment by JordanB-1337** [comment]
Well it's true ;P
